print(len("three"))
print("This" + " " + "is a " + "string.")
print(len("This" + " " + "is a " + "string."))
print("antidisestablishmentarianism"[7:20])
print(len("antidisestablishmentarianism"[7:20]))
